@baseUrl = http://localhost:3000

### Read all films
GET {{baseUrl}}/films

### read minimum duration film
GET {{baseUrl}}/films?minimum-duration=189

### read film with id = ?
GET {{baseUrl}}/films/2

### Create one 
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "ballerina",
    "director": "Lee Chung-hyun",
    "duration": 93,
    "budget": 40,
    "description": "L'histoire suit Ok-ju, une ancienne garde du corps qui cherche à se venger de ceux qui ont causé la mort de sa meilleure amie, Min-hee. Dévastée par cette perte, Ok-ju plonge dans un parcours brutal pour traquer les responsables, dévoilant au passage sa nature impitoyable. Le film se caractérise par son ambiance sombre, ses visuels néon, et une bande-son percutante, contribuant à créer une atmosphère intense tout au long du récit",
    "imageUrl": "https://example.com/???.jpg"
}